package main

import (
	"os"
	"os/signal"
	"syscall"

	"github.com/goravel/framework/facades"

	"books-database/bootstrap"
	_ "books-database/docs" // Swagger docs (generated by: go run . artisan swagger:generate)
)

// @title           Library Management API
// @version         1.0
// @description     A comprehensive library management system API with books, lenders, users, roles, and permissions management.
// @description     Supports JWT authentication, role-based access control, and scoped permissions.

// @contact.name   API Support
// @contact.email  support@library.com

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:3000
// @BasePath  /api

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// This bootstraps the framework and gets it ready for use.
	bootstrap.Boot()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	// Start http server by facades.Route().
	go func() {
		if err := facades.Route().Run(); err != nil {
			facades.Log().Errorf("Route Run error: %v", err)
		}
	}()

	// Listen for the OS signal
	go func() {
		<-quit
		if err := facades.Route().Shutdown(); err != nil {
			facades.Log().Errorf("Route Shutdown error: %v", err)
		}

		os.Exit(0)
	}()

	select {}
}
