import React, { useState } from 'react';
import { Head, router } from '@inertiajs/react';
import { CheckCircle, XCircle, Copy, Mail } from 'lucide-react';
import {
  Application,
  ApplicationListResponse,
  ApplicationListRequest,
} from '@/types/application';
import { CrudPage } from '@/components/Crud/CrudPage';
import {
  ApplicationDetailView,
  applicationColumns,
  applicationColumnsMobile,
  applicationFilters,
} from './sections';
import { useIsMobile } from '@/hooks/use-mobile';
import Admin from '@/layouts/Admin';
import { CrudAction } from '@/types/crud';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

// Props interface for the Application Index page
interface ApplicationIndexProps {
  data: ApplicationListResponse;
  filters: ApplicationListRequest;
  permissions: {
    canCreate: boolean;
    canEdit: boolean;
    canDelete: boolean;
  };
  meta?: {
    pagination: {
      defaultPageSize: number;
      maxPageSize: number;
      allowedSizes: number[];
    };
  };
}

export default function ApplicationIndex({
  data,
  filters,
  permissions,
  meta
}: ApplicationIndexProps) {
  const isMobile = useIsMobile();
  const [showRejectionDialog, setShowRejectionDialog] = useState(false);
  const [showWelcomeEmailDialog, setShowWelcomeEmailDialog] = useState(false);
  const [selectedApplication, setSelectedApplication] = useState<Application | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [needsReload, setNeedsReload] = useState(false);
  const [rejectionReason, setRejectionReason] = useState<string>('');
  const [showApproveConfirmDialog, setShowApproveConfirmDialog] = useState(false);
  const [showSignupRejectConfirmDialog, setShowSignupRejectConfirmDialog] = useState(false);
  const [welcomeEmailData, setWelcomeEmailData] = useState<{
    username: string;
    password: string;
    loginUrl: string;
    applicantName: string;
  } | null>(null);

  const handleRefresh = () => {
    router.reload({ only: ['data'] });
  };

  const handleApproveClick = (application: Application) => {
    if (application.status !== 'Pending') {
      toast.info('Application has already been ' + application.status);
      return;
    }
    setSelectedApplication(application);
    setShowApproveConfirmDialog(true);
  };

  const handleApprove = async () => {
    if (!selectedApplication) return;

    setIsLoading(true);
    try {
      const response = await fetch(`/api/applications/${selectedApplication.id}/approve`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
        },
        body: JSON.stringify({}),
      });

      const data = await response.json();

      if (response.ok) {
        toast.success(data.message || 'Application approved successfully');
        setShowApproveConfirmDialog(false);

        // Show welcome email dialog with user credentials if available
        if (data.data?.user?.email) {
          setWelcomeEmailData({
            username: data.data.user.email,
            password: data.data.user.password || 'Generated by system',
            loginUrl: window.location.origin + '/login',
            applicantName: selectedApplication.registrant_name || '',
          });
          setShowWelcomeEmailDialog(true);
          setNeedsReload(true);
        } else {
          router.reload({ only: ['data'] });
        }

        setSelectedApplication(null);
      } else {
        toast.error(data.message || 'Failed to approve application');
      }
    } catch (error) {
      console.error('Error approving application:', error);
      toast.error('Failed to approve application');
    } finally {
      setIsLoading(false);
    }
  };

  // Handle reject click
  const handleRejectClick = (application: Application) => {
    if (application.status !== 'Pending') {
      toast.info('Application has already been ' + application.status);
      return;
    }
    setSelectedApplication(application);
    setRejectionReason('');

    // Signup applications need confirmation before showing rejection dialog
    if (application.type === 'signup') {
      setShowSignupRejectConfirmDialog(true);
      return;
    }

    // Other applications go directly to rejection reason dialog
    setShowRejectionDialog(true);
  };

  // Handle reject submission
  const handleReject = async () => {
    if (!selectedApplication) return;

    if (!rejectionReason.trim()) {
      toast.info('Please provide a reason for rejection');
      return;
    }

    setIsLoading(true);
    try {
      const response = await fetch(`/api/applications/${selectedApplication.id}/reject`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
        },
        body: JSON.stringify({ reason: rejectionReason.trim() }),
      });

      const data = await response.json();

      if (response.ok) {
        toast.success(data.message || 'Application rejected successfully');
        setShowRejectionDialog(false);
        setSelectedApplication(null);
        setRejectionReason('');
        router.reload({ only: ['data'] });
      } else {
        toast.error(data.message || 'Failed to reject application');
      }
    } catch (error) {
      console.error('Error rejecting application:', error);
      toast.error('Failed to reject application');
    } finally {
      setIsLoading(false);
    }
  };

  // Generate welcome email text
  const generateWelcomeEmail = () => {
    if (!welcomeEmailData) return '';

    return `Subject: Welcome - Your Account Has Been Approved

Dear ${welcomeEmailData.applicantName},

Congratulations! Your application has been approved and your account has been successfully created.

Your account details:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Username: ${welcomeEmailData.username}
Password: ${welcomeEmailData.password}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You can now log in to your account using the following link:
${welcomeEmailData.loginUrl}

For security reasons, we recommend changing your password after your first login.

If you have any questions or need assistance, please don't hesitate to contact our support team.

Best regards,
The Team`;
  };

  const handleCopyWelcomeEmail = async () => {
    const emailText = generateWelcomeEmail();
    try {
      await navigator.clipboard.writeText(emailText);
      toast.success('Welcome email copied to clipboard');
    } catch (error) {
      toast.error('Failed to copy to clipboard');
    }
  };

  // Handle welcome email dialog close
  const handleWelcomeEmailDialogClose = (open: boolean) => {
    setShowWelcomeEmailDialog(open);
    if (!open && needsReload) {
      setNeedsReload(false);
      router.reload({ only: ['data'] });
    }
  };

  // Custom row actions for approve/reject - only show for pending applications
  const customActions: CrudAction<Application>[] = permissions.canEdit ? [
    {
      key: 'approve',
      label: 'Approve',
      icon: <CheckCircle className="w-4 h-4" />,
      onClick: handleApproveClick,
      hidden: (app) => app.status !== 'Pending',
    },
    {
      key: 'reject',
      label: 'Reject',
      icon: <XCircle className="w-4 h-4" />,
      onClick: handleRejectClick,
      hidden: (app) => app.status !== 'Pending',
    },
  ] : [];

  return (
    <Admin title={"Application"}>
      <Head title="Application - Management" />

      <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
        {/* Main CRUD Component */}
        <div className="px-0">
          <CrudPage<Application>
            data={data}
            filters={filters}
            title="Applications"
            resourceName="applications"
            columns={isMobile ? applicationColumnsMobile : applicationColumns}
            customFilters={applicationFilters}
            paginationConfig={meta?.pagination}
            detailView={ApplicationDetailView}
            onRefresh={handleRefresh}
            canView={true}
            readOnly={true}
            actions={customActions}
          />
        </div>
      </div>

      {/* Approval Confirmation Dialog */}
      <Dialog open={showApproveConfirmDialog} onOpenChange={setShowApproveConfirmDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Approve Application</DialogTitle>
            <DialogDescription>
              Are you sure you want to approve this application?
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {selectedApplication && (
              <div className="bg-muted p-3 rounded-md text-sm space-y-1">
                <p><strong>Organization:</strong> {selectedApplication.sme}</p>
                <p><strong>Applicant:</strong> {selectedApplication.registrant_name}</p>
                <p><strong>Email:</strong> {selectedApplication.email}</p>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowApproveConfirmDialog(false);
                setSelectedApplication(null);
              }}
              disabled={isLoading}
            >
              Cancel
            </Button>
            <Button
              onClick={handleApprove}
              disabled={isLoading}
            >
              {isLoading ? 'Approving...' : 'Approve Application'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Rejection Dialog */}
      <Dialog open={showRejectionDialog} onOpenChange={setShowRejectionDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reject Application</DialogTitle>
            <DialogDescription>
              Reject this application. The applicant will be notified.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="rejection-reason">Reason for Rejection *</Label>
              <Textarea
                id="rejection-reason"
                placeholder="Please provide a reason for rejecting this application..."
                value={rejectionReason}
                onChange={(e) => setRejectionReason(e.target.value)}
                className="min-h-[100px]"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowRejectionDialog(false)} disabled={isLoading}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleReject} disabled={isLoading || !rejectionReason.trim()}>
              {isLoading ? 'Rejecting...' : 'Reject Application'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Welcome Email Dialog */}
      <Dialog open={showWelcomeEmailDialog} onOpenChange={handleWelcomeEmailDialogClose}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Mail className="h-5 w-5" />
              Welcome Email Preview
            </DialogTitle>
            <DialogDescription>
              Copy this welcome email to send to the applicant with their login credentials.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <Textarea
              value={generateWelcomeEmail()}
              readOnly
              className="min-h-[400px] font-mono text-sm"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => handleWelcomeEmailDialogClose(false)}>
              Close
            </Button>
            <Button onClick={handleCopyWelcomeEmail}>
              <Copy className="h-4 w-4 mr-2" />
              Copy to Clipboard
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Signup Rejection Confirmation Dialog */}
      <Dialog open={showSignupRejectConfirmDialog} onOpenChange={setShowSignupRejectConfirmDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reject Signup Application</DialogTitle>
            <DialogDescription>
              Are you sure you want to reject this signup application?
              The applicant will not be able to access the system.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {selectedApplication && (
              <div className="bg-muted p-3 rounded-md text-sm space-y-1">
                <p><strong>Organization:</strong> {selectedApplication.sme}</p>
                <p><strong>Applicant:</strong> {selectedApplication.registrant_name}</p>
                <p><strong>Email:</strong> {selectedApplication.email}</p>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowSignupRejectConfirmDialog(false);
                setSelectedApplication(null);
              }}
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={() => {
                setShowSignupRejectConfirmDialog(false);
                setShowRejectionDialog(true);
              }}
            >
              Yes, Proceed to Rejection
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Admin>
  );
}
