import React, { useState } from 'react';
import { Head, router } from '@inertiajs/react';
import { CheckCircle, XCircle, Plus, Copy, Mail } from 'lucide-react';
import {
  Application,
  ApplicationListResponse,
  ApplicationListRequest
} from '@/types/application';
import { CrudPage } from '@/components/Crud/CrudPage';
import {
  ApplicationDetailView,
  applicationColumns,
  applicationColumnsMobile,
  applicationFilters
} from './sections';
import { useIsMobile } from '@/hooks/use-mobile';
import Admin from '@/layouts/Admin';
import { CrudAction } from '@/types/crud';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { SmeCreateForm } from '@/pages/Sme/sections';
import { Textarea } from '@/components/ui/textarea';

// Props interface for the Application Index page
interface ApplicationIndexProps {
  data: ApplicationListResponse;
  filters: ApplicationListRequest;
  permissions: {
    canCreate: boolean;
    canEdit: boolean;
    canDelete: boolean;
  };
  meta?: {
    pagination: {
      defaultPageSize: number;
      maxPageSize: number;
      allowedSizes: number[];
    };
  };
}

interface Sme {
  id: number;
  name: string;
  usme_number: string;
}

export default function ApplicationIndex({
  data,
  filters,
  permissions,
  meta
}: ApplicationIndexProps) {
  const isMobile = useIsMobile();
  const [showApprovalDialog, setShowApprovalDialog] = useState(false);
  const [showRejectionDialog, setShowRejectionDialog] = useState(false);
  const [showCreateSmeDialog, setShowCreateSmeDialog] = useState(false);
  const [showWelcomeEmailDialog, setShowWelcomeEmailDialog] = useState(false);
  const [selectedApplication, setSelectedApplication] = useState<Application | null>(null);
  const [selectedSmeId, setSelectedSmeId] = useState<string>('');
  const [smes, setSmes] = useState<Sme[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingSmes, setIsLoadingSmes] = useState(false);
  const [needsReload, setNeedsReload] = useState(false);
  const [welcomeEmailData, setWelcomeEmailData] = useState<{
    username: string;
    password: string;
    loginUrl: string;
    smeName: string;
    applicantName: string;
  } | null>(null);

  const handleRefresh = () => {
    router.reload({ only: ['data'] });
  };

  const fetchSmes = async () => {
    setIsLoadingSmes(true);
    try {
      const response = await fetch('/api/smes', {
        headers: {
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
        },
      });

      if (response.ok) {
        const data = await response.json();
        setSmes(data.data?.data || []);
      } else {
        toast.info('Failed to load SMEs');
      }
    } catch (error) {
      console.error('Error fetching SMEs:', error);
      toast.info('Failed to load SMEs');
    } finally {
      setIsLoadingSmes(false);
    }
  };

  const handleApproveClick = (application: Application) => {
    if (application.status !== 'Pending') {
      toast.info('Application has already been ' + application.status);
      return;
    }
    setSelectedApplication(application);
    setShowApprovalDialog(true);
    fetchSmes();
  };

  const handleApprove = async () => {
    if (!selectedApplication) return;

    if (!selectedSmeId) {
      toast.info('Please select an SME');
      return;
    }

    setIsLoading(true);
    try {
      const response = await fetch(`/api/applications/${selectedApplication.id}/approve`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
        },
        body: JSON.stringify({ sme_id: parseInt(selectedSmeId) }),
      });

      const data = await response.json();

      if (response.ok) {
        toast.success(data.message || 'Application approved successfully');
        setShowApprovalDialog(false);

        // Show welcome email dialog with user credentials
        const selectedSme = smes.find(s => s.id === parseInt(selectedSmeId));
        setWelcomeEmailData({
          username: data.data?.user?.email,
          password: data.data?.user?.password || 'Generated by system',
          loginUrl: window.location.origin + '/login',
          smeName: selectedSme?.name || '',
          applicantName: selectedApplication.registrant_name || `${selectedApplication.first_name} ${selectedApplication.last_name}`,
        });
        setShowWelcomeEmailDialog(true);
        setNeedsReload(true);

        setSelectedApplication(null);
        setSelectedSmeId('');
      } else {
        toast.error(data.message || 'Failed to approve application');
      }
    } catch (error) {
      console.error('Error approving application:', error);
      toast.error('Failed to approve application');
    } finally {
      setIsLoading(false);
    }
  };

  // Handle reject click
  const handleRejectClick = (application: Application) => {
    if (application.status !== 'Pending') {
      toast.info('Application has already been ' + application.status);
      return;
    }
    setSelectedApplication(application);
    setShowRejectionDialog(true);
  };

  // Handle reject submission
  const handleReject = async () => {
    if (!selectedApplication) return;

    setIsLoading(true);
    try {
      const response = await fetch(`/api/applications/${selectedApplication.id}/reject`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
        },
      });

      const data = await response.json();

      if (response.ok) {
        toast.success(data.message || 'Application rejected successfully');
        setShowRejectionDialog(false);
        setSelectedApplication(null);
        router.reload({ only: ['data'] });
      } else {
        toast.error(data.message || 'Failed to reject application');
      }
    } catch (error) {
      console.error('Error rejecting application:', error);
      toast.error('Failed to reject application');
    } finally {
      setIsLoading(false);
    }
  };

  // Handle SME creation success
  const handleSmeCreated = async (newSme: any) => {
    toast.success('SME created successfully');
    setShowCreateSmeDialog(false);
    await fetchSmes();
    if (newSme?.id) {
      setSelectedSmeId(newSme.id.toString());
    }
  };

  // Generate welcome email text
  const generateWelcomeEmail = () => {
    if (!welcomeEmailData) return '';

    return `Subject: Welcome to the MSME Database - Your Account Has Been Approved

Dear ${welcomeEmailData.applicantName},

Congratulations! Your application has been approved and your account has been successfully created.

Your account details:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SME: ${welcomeEmailData.smeName}
Username: ${welcomeEmailData.username}
Password: ${welcomeEmailData.password}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You can now log in to your account using the following link:
${welcomeEmailData.loginUrl}

For security reasons, we recommend changing your password after your first login.

If you have any questions or need assistance, please don't hesitate to contact our support team.

Best regards,
SMEDI Team`;
  };

  const handleCopyWelcomeEmail = async () => {
    const emailText = generateWelcomeEmail();
    try {
      await navigator.clipboard.writeText(emailText);
      toast.success('Welcome email copied to clipboard');
    } catch (error) {
      toast.error('Failed to copy to clipboard');
    }
  };

  // Handle welcome email dialog close
  const handleWelcomeEmailDialogClose = (open: boolean) => {
    setShowWelcomeEmailDialog(open);
    if (!open && needsReload) {
      setNeedsReload(false);
      router.reload({ only: ['data'] });
    }
  };

  // Custom row actions for approve/reject
  const customActions: CrudAction<Application>[] = permissions.canEdit ? [
    {
      key: 'approve',
      label: 'Approve',
      icon: <CheckCircle className="w-4 h-4" />,
      onClick: handleApproveClick,
    },
    {
      key: 'reject',
      label: 'Reject',
      icon: <XCircle className="w-4 h-4" />,
      onClick: handleRejectClick,
    },
  ] : [];

  return (
    <Admin title={"Application"}>
      <Head title="Application - Management" />

      <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
        {/* Main CRUD Component */}
        <div className="px-0">
          <CrudPage<Application>
            data={data}
            filters={filters}
            title="Applications"
            resourceName="applications"
            columns={isMobile ? applicationColumnsMobile : applicationColumns}
            customFilters={applicationFilters}
            paginationConfig={meta?.pagination}
            detailView={ApplicationDetailView}
            onRefresh={handleRefresh}
            canView={true}
            readOnly={true}
            actions={customActions}
          />
        </div>
      </div>

      {/* Approval Dialog */}
      <Dialog open={showApprovalDialog} onOpenChange={setShowApprovalDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Approve Application</DialogTitle>
            <DialogDescription>
              Select an SME to associate with this application. A user account will be created for the applicant.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="sme">Select SME *</Label>
              <Select value={selectedSmeId} onValueChange={setSelectedSmeId} disabled={isLoadingSmes}>
                <SelectTrigger>
                  <SelectValue placeholder={isLoadingSmes ? "Loading SMEs..." : "Select an SME"} />
                </SelectTrigger>
                <SelectContent>
                  {smes.map((sme) => (
                    <SelectItem key={sme.id} value={sme.id.toString()}>
                      {sme.name} ({sme.usme_number})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Button
                variant="outline"
                className="w-full"
                onClick={() => setShowCreateSmeDialog(true)}
              >
                <Plus className="h-4 w-4 mr-2" />
                Create New SME
              </Button>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowApprovalDialog(false)} disabled={isLoading}>
              Cancel
            </Button>
            <Button onClick={handleApprove} disabled={isLoading || !selectedSmeId}>
              {isLoading ? 'Approving...' : 'Approve Application'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Rejection Dialog */}
      <Dialog open={showRejectionDialog} onOpenChange={setShowRejectionDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reject Application</DialogTitle>
            <DialogDescription>
              Are you sure you want to reject this application? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowRejectionDialog(false)} disabled={isLoading}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleReject} disabled={isLoading}>
              {isLoading ? 'Rejecting...' : 'Reject Application'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Welcome Email Dialog */}
      <Dialog open={showWelcomeEmailDialog} onOpenChange={handleWelcomeEmailDialogClose}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Mail className="h-5 w-5" />
              Welcome Email Preview
            </DialogTitle>
            <DialogDescription>
              Copy this welcome email to send to the applicant with their login credentials.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <Textarea
              value={generateWelcomeEmail()}
              readOnly
              className="min-h-[400px] font-mono text-sm"
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => handleWelcomeEmailDialogClose(false)}>
              Close
            </Button>
            <Button onClick={handleCopyWelcomeEmail}>
              <Copy className="h-4 w-4 mr-2" />
              Copy to Clipboard
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Create SME Dialog */}
      <Dialog open={showCreateSmeDialog} onOpenChange={setShowCreateSmeDialog}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Create New SME</DialogTitle>
            <DialogDescription>
              Create a new SME to associate with this application.
            </DialogDescription>
          </DialogHeader>
          <SmeCreateForm
            onSuccess={handleSmeCreated}
            onError={(error) => toast.error(error?.message || 'Failed to create SME')}
            onCancel={() => setShowCreateSmeDialog(false)}
          />
        </DialogContent>
      </Dialog>
    </Admin>
  );
}
